version: "3.9"

services:
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_DB: $${POSTGRES_DB:=sistemacatalogo}
      POSTGRES_USER: $${POSTGRES_USER:=postgres}
      POSTGRES_PASSWORD: $${POSTGRES_PASSWORD:=postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  springboot:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION: true
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
